<?
header("Content-type: image/jpg");
header("Content-length: 291");
echo base64_decode(
'/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBAQFBAYFBQYJBg'.
'UGCQsIBgYICwwKCgsKCgwQDAwMDAwMEAwODxAPDgwTExQUExMc'.
'GxsbHCAgICAgICAgICD/2wBDAQcHBw0MDRgQEBgaFREVGiAgIC'.
'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'.
'ICAgICAgICD/wAARCAAQABADAREAAhEBAxEB/8QAFQABAQAAAA'.
'AAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QA'.
'FgEBAQEAAAAAAAAAAAAAAAAAAAYI/8QAFBEBAAAAAAAAAAAAAA'.
'AAAAAAAP/aAAwDAQACEQMRAD8AnSOaRAAAf//Z'.
'');
?>